services:
  vuln-app-cve-2024-29041:
    build:
      context: .
      dockerfile: ./vuln-app/Dockerfile
    ports:
      - "8002:3000"
  normal-app-cve-2024-29041:
    build:
      context: .
      dockerfile: ./normal-app/Dockerfile
    ports:
      - "8003:3000"
